// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyX5ARlSh8MtVA6ASylLh4_rtHGBGLITc',
    appId: '1:48323504620:web:015c20cb6bd0e0840ab8c9',
    messagingSenderId: '48323504620',
    projectId: 'game-catch-coin',
    authDomain: 'game-catch-coin.firebaseapp.com',
    storageBucket: 'game-catch-coin.firebasestorage.app',
    measurementId: 'G-VT4S6NVQ7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKu-8gt-bsQHAHdFvcV--0ieDDVEdGsOo',
    appId: '1:48323504620:android:5f1ce3e14d5f8e500ab8c9',
    messagingSenderId: '48323504620',
    projectId: 'game-catch-coin',
    storageBucket: 'game-catch-coin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZU6iAZYG7ZPKoXpP6kEbzvwV-zC52mOs',
    appId: '1:48323504620:ios:00caea3e06b9edbc0ab8c9',
    messagingSenderId: '48323504620',
    projectId: 'game-catch-coin',
    storageBucket: 'game-catch-coin.firebasestorage.app',
    iosBundleId: 'com.example.utsGameCatchCoin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZU6iAZYG7ZPKoXpP6kEbzvwV-zC52mOs',
    appId: '1:48323504620:ios:00caea3e06b9edbc0ab8c9',
    messagingSenderId: '48323504620',
    projectId: 'game-catch-coin',
    storageBucket: 'game-catch-coin.firebasestorage.app',
    iosBundleId: 'com.example.utsGameCatchCoin',
  );
}
